[project]
name = "story-scraper"
version = "0.1.0"
description = "A small package for retrieving collections of html formatted short stories and generating custom epub digests"
authors = [
    { name = "Caroline Jeffra", email = "caroline.jeffra@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
story-scraper = "story_scraper:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
